### ISSUE TITLE
Speech audiometry spline acts weird when intensities are close together

### ISSUE THREAD

**Issue by martinmodrak** [drwaseemsheikh/audiometry#10]
![image](https://user-images.githubusercontent.com/9483603/75053428-8d13bb00-54d1-11ea-8d2b-8d668b053e84.png)

I don't think this is an important issue, as I assume there would mostly be larger steps in intensity, just wanted to let you know about it.

**Comment by drwaseemsheikh** [comment]
The intensities are never close like that in actual hearing tests. Therefore, not important.

**Comment by drwaseemsheikh** [comment]
The intensities are never close like that in actual hearing tests, therefore, won't be fixed. The curve has to be smooth as the per the audiometry standards.
