### ISSUE TITLE
Printing is wasteful

### ISSUE THREAD

**Issue by martinmodrak** [drwaseemsheikh/audiometry#11]
I understand that the approach to print data via printing the on-screen controls was chosen for simplicity and in that it is a nice hack. However I think it should not print components that do not contain any data, as currently printing a data for a single patient where one test was conducted actually gives me 15 pages.

**Comment by drwaseemsheikh** [comment]
The software printing is functional. Changing the print functionality to not print using GUI would require months of coding effort from my side which I don't have.

Again, I will reiterate to you that when you review open-source projects, you are not looking for the perfect software. We are not paid to spend years to write such software. If it's functional and solves an important medical problem that makes people's lives better in third world countries, you need to acknowledge that fact.

**Comment by martinmodrak** [comment]
I am sorry if my description was not clear. I am completely OK with using GUI for printing. My suggestion is that simply in `MainWindow.PrintGuiBtn_Click` where you have 

```
var thirdPageContent = PrintUtility.CreatePrintPageContent(pageSize, PureToneAMCanvas, ptamTabCtrl, 0, 3, "Pure Tone Audiometry");
document.Pages.Add(thirdPageContent);
```

you change it to something like:
```
if(PureToneDataPresent()) {
  var thirdPageContent = PrintUtility.CreatePrintPageContent(pageSize, PureToneAMCanvas, ptamTabCtrl, 0, 3, "Pure Tone Audiometry");
  document.Pages.Add(thirdPageContent);
}
```
where `PureToneDataPresent()` checks if at least one of the boxes on the tab is non-empty. Similarly for other tabs so that the software doesn't print many pages of empty GUI. I don't insist on implementing it exactly this way, just trying to show that the effect can be achieved with a small code change.

**Comment by drwaseemsheikh** [comment]
Printing is functional. This is a minor issue.
