### ISSUE TITLE
I can't find the research-related functionality

### ISSUE THREAD

**Issue by martinmodrak** [drwaseemsheikh/audiometry#12]
The JOSS paper states that: 
> 1. The software can be used to compare the sensitivity (true-positive rate) and specificity
> (true-negative rate) of various hearing test equipment and methods. For example,
> questions like how reliable is a pure-tone audiometry test performed by a smartphone or
> a tablet when compared to a benchmark calibrated audiometer can be easily answered
> by using this software.
> 2. The software can be used to determine important correlations between lifestyle, work
> conditions, and demographics; and the types of hearing loss.
> 3. The software can be used to measure the efficacy of a certain treatment, intervention,
> or equipment on the progression of a hearing loss.

I was however unable to locate any functionality related to those tasks neither in code nor in documentation. Where can I find those?

**Comment by drwaseemsheikh** [comment]
1. You can compare the results of two different hearing test instruments by storing the data from both the instruments and opening their respective results and looking at the changes.

2. You can store the data from individuals from different professions and compare their audiograms or scores and draw conclusions.

3. You can store a progression of tests over time while a patient is under some treatment and look at the plots and data to draw conclusions about the efficacy of the treatment.

**Comment by martinmodrak** [comment]
Maybe this is a misunderstanding, but you seem to imply that the software doesn't let me to do this directly - I see how I can store results from different instruments, print the curves and compare them by eye, but it seems that the program doesn't have a "Compare instruments" function that would e.g. overlay "Pure tone" curves from two instruments or compute some distance metrics between the two instruments?

Similarly when I "store the data from individuals from different professions and compare" or follow a patient through treatment, it seems that I need to either do the comparisons manually or open the associated SQLite database in a different program and perform the analysis there. Is that correct?

**Comment by drwaseemsheikh** [comment]
The research related functionality has been explained in the threads numerous times.
