### ISSUE TITLE
Installer fails when updating

### ISSUE THREAD

**Issue by martinmodrak** [drwaseemsheikh/audiometry#14]
I downloaded the installer for the updated version of the software. It shows an error message:

> Another version of this product is already installed.  Installation of this version cannot continue.  To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel.

When I remove the older installation, the installation proceeds. I am however unsure if that also didn't delete the application data.

This is a minor issue.

**Comment by drwaseemsheikh** [comment]
Uninstaller doesn't delete the database. You can copy the database file after uninstall and then overwrite after the install. No data is lost.
