### ISSUE TITLE
There is no link to any documentation

### ISSUE THREAD

**Issue by dvberkel** [drwaseemsheikh/audiometry#2]
The review process asks me to check for documentation. There is no link to any documentation, and other than the README and your article, I couldn't find any.

Could you link to the documentation in the README?

**Comment by dvberkel** [comment]
Going over all the documentation section in the [review](https://github.com/openjournals/joss-reviews/issues/2016#), I seem to be missing a number of the requested items. Am I looking in the right place, or are there some items missing?

**Comment by waseemsheikh** [comment]
Hi!

There are two types of documentation in the repository:

1. The Doxygen generated API files are under \Docs\Doxygen. This contains folders for both html and latex generated files for the software documentation. I don't know exactly how to add a link to these folders in README files. If you could please guide me, I will appreciate it.

2. The second document is the full-length paper which explains the software design in much more detail. That paper is under \paper\full_paper.pdf. Again, I don't know how to put a link to this file in the README file. If you could please guide me, I will appreciate it.

Waseem

**Comment by drwaseemsheikh** [comment]
Hi!

There are two types of documentation in the repository:

The Doxygen generated API files are under \Docs\Doxygen. This contains folders for both html and latex generated files for the software documentation. I don't know exactly how to add a link to these folders in README files. If you could please guide me, I will appreciate it.

The second document is the full-length paper which explains the software design in much more detail. That paper is under \paper\full_paper.pdf. Again, I don't know how to put a link to this file in the README file. If you could please guide me, I will appreciate it.

Waseem

**Comment by dvberkel** [comment]
I think the easiest think to do is to use the GitHub pages functionality.

For this the work I think it is best to rename the `Docs` folder to `docs`. Next, go to the settings page of your project on GitHub and scroll to the section "GitHub Pages". You will find a dropdown under source where you can choose:

> master branch /docs folder

Once chosen, it will provide you with a link where the documentation is hosted. Everything for which you need a link to should then be placed inside the `docs` directory. 

For more information look at this [blog post](https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/). If you need more help, let me know.

I will take a look at the documentation you pointed out

**Comment by drwaseemsheikh** [comment]
Let me work on it right now and if I have any questions regarding moving and renaming folders, I will ask. I am not an expert in Github, so I will definitely appreciate your help if I encounter any issues.

**Comment by drwaseemsheikh** [comment]
Thank you for the blog post. That really helped. So, I have renamed the Docs folder to docs and followed the steps to link GitHub Pages to my Doxygen Generated Documentation. You can check it at:
https://drwaseemsheikh.github.io/audiometry/

Please note that you will have to go under Classes tab to see the description of each class.

Please let me know if I need to make any other changes. Thanks!

**Comment by dvberkel** [comment]
I am glad to hear that you worked out how to publish the documentation to GitHub pages. Concerning the documentation, I am still missing the following items

* **Installation instructions**: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
* **Community guidelines**: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

For the first, I would a like to see a paragraph in the README detailing the steps how to install the software. I.e. where to get the software, how to setup the required dependencies if any, how to actually install the software.

For the second, there is a convention that a file `CONTRIBUTING.md` in the top of the project describes how to contribute. I searched for an [example](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) to give you a some sense of what to expect. 
It does not have to be as extensive, but mentioning where to seek help and reports bugs is a good start.

Other than the above points, to me everything looks good.

**Comment by drwaseemsheikh** [comment]
I have addressed both of your concerns. Thank you for providing directions.
1. Added an Installation Section in README.md explaining how to install the software.
2. Added a folder .github (following the convention) and inside it added two files. The first one, bug_report.md provides a template for reporting bugs. The second one, feature_request.md provides a template for submitting a feature request.

Please let me know if anything else needs changing.

**Comment by dvberkel** [comment]
This looks good to me. I am closing this issue
