### ISSUE TITLE
Move installer binaries to relases

### ISSUE THREAD

**Issue by martinmodrak** [drwaseemsheikh/audiometry#3]
Having binaries in version control is usually discouraged as they can reduce the performance of Git and make the size of the repository grow beyond desirable. It is also easy to let the binaries slip out of sync with the code, if they are not regenerated automatically.

Instead, IMHO a better practice is to use the "Releases" feature of GitHub, create a release and attach the binaries to it.

This is a minor issue and I do not insist on you following this recommendation.

**Comment by drwaseemsheikh** [comment]
I don't think this affects the functionality of the software and given my time constraints, I am unable to do so.
