### ISSUE TITLE
Copyright warning in installer

### ISSUE THREAD

**Issue by martinmodrak** [drwaseemsheikh/audiometry#4]
The installer gives a harsh copyright warning:

![image](https://user-images.githubusercontent.com/9483603/75049572-ba109f80-54ca-11ea-8621-262abcb229fb.png)

Since this is an open-source software that is free to redistribute I don't think it makes any sense to have such a warning and I believe you should remove it.

**Comment by drwaseemsheikh** [comment]
This comes built-in with the Windows MSI installer. I couldn't find a way to get rid of it.

**Comment by drwaseemsheikh** [comment]
Minor issue and doesn't affect the functionality of the software.
