### ISSUE TITLE
Potentially weak security setup

### ISSUE THREAD

**Issue by martinmodrak** [drwaseemsheikh/audiometry#5]
So maybe I am missing something, because the password protection of the database is not really documented, but it appears to provide only very rudimentary security-by-obscurity mechanism to protect stored data. 

From reading the code it appears that the plaintext password can be retrieved from the registry at any time, so if an attacker reads the registry and the source code here at GitHub, they can get access to the full database.  A step in a better direction would be to only ever store the username and the plaintext password in memory and use the databases authentication mechanism as the authentication mechanism to the whole software. I believe SQLLite has well implemented cryptography and thus relying on it can spare you some mistakes. Other approaches are definitely possible.

I understand that the current procedure might be enough to prevent tampering by unskilled attacker and this might be enough for the desire use cases - I am no expert on privacy on patient data neither I understand security deeply, so I am unsure what the relevant standards are.

**Comment by drwaseemsheikh** [comment]
Martin,

You are not understanding the password protection mechanism correctly. Please read the full-length paper in the fame folder as the JOSS paper or the soruce code to see how password protection works. You are incorrect in your remarks that it only provides 'rudimentary' security mechanism and that the plaintext password can be retrieved from the registry. The plaintext password is never stored in the registry. It is the hashed and encrypted password that is stored in the registry. The software already uses the SQLLite cryptography API to encrypt the database to which you alluded. I would suggest reading the code and documentation more carefully.

Another point. We are not paid to write this software. We all have other full-time jobs and we do this out of goodwill so you need to keep that in consideration while splitting hairs. Sure, this software is not perfect. But is it functional. Absolutely.

**Comment by martinmodrak** [comment]
Sorry, you are correct, I missed that you use the ProtectedData API underneath to ensure security, this is a sensible approach.
