### ISSUE TITLE
Cannot save patient + unhelpful message

### ISSUE THREAD

**Issue by martinmodrak** [drwaseemsheikh/audiometry#6]
I am not a medical proffessional, but I tried to setup a simple patient record with not everything filled in:

![image](https://user-images.githubusercontent.com/9483603/75051936-0eb61980-54cf-11ea-8555-ab82fc490921.png)

After clicking "Save" I get:

![image](https://user-images.githubusercontent.com/9483603/75052036-3e652180-54cf-11ea-8f26-998e447a9e14.png)

The message should IMHO tell me what am I missing.

Then, if I fill in the "Account number" field, but let the cursor (focus) stay in the text area, the error still appears. When I click outside and then click "Save" the save is succesful. This looks like a bug.

It appears that "Account Number" is a vital field that has to be filled in. I would therefor suggest it is put at the very top of the patient form.

**Comment by drwaseemsheikh** [comment]
The software is telling you exactly what is missing. You provided a blank account number. Any layman would know that you can't store a medical record with an account number. 

The default WPF textbox behavior is that binding is fired when control leaves a textbox. I would suggest asking Microsoft to make changes to that.

I am unable to change the layout of GUI, which I believe is not important. The fact that account number is a vital field is self-explanatory.

**Comment by drwaseemsheikh** [comment]
Bug fixed.
