### ISSUE TITLE
Duplicated menus

### ISSUE THREAD

**Issue by martinmodrak** [drwaseemsheikh/audiometry#8]
The application has two menus on top:

![image](https://user-images.githubusercontent.com/9483603/75052581-2215b480-54d0-11ea-8778-a560c9ba2519.png)

It appears both provide the same functionality. I would suggest removing one (The one below is IMHO more user friendly so I would keep this one).

**Comment by drwaseemsheikh** [comment]
The software is functional. Having duplicate menu items do not affect the functionality of the software. I don't have time to make this change.

**Comment by drwaseemsheikh** [comment]
A minor issue that doesn't affect the functionality of the software.
