### ISSUE TITLE
Unnecessary overwrite confirmations

### ISSUE THREAD

**Issue by martinmodrak** [drwaseemsheikh/audiometry#9]
Whenever I try to save patient's data I get dialog similar to:

![image](https://user-images.githubusercontent.com/9483603/75052817-7e78d400-54d0-11ea-95a4-060e80e01225.png)

This feels counterproductive - I would expect such dialogs to only appear if for example try to create a patient record with the same account number as another in the database. Saving should IMHO just happen. Spamming the user with too many confirmations will just lead to them ignoring those and mindlesssly clicking "Yes" - including the cases when they do something actually dangerous (for example opening a new patient without saving the currently opened one).

The dialog also appears even if I made no changes to the patient.

Further the message dialog 
![image](https://user-images.githubusercontent.com/9483603/75053071-f34c0e00-54d0-11ea-85fb-f2460a571f19.png)

is IMHO redundant and distracts from work. I would suggest you instead have some area for messages that don't necessarily require attention (like this one) and show them there without requiring user input and let them fade (either over time or when the user makes additional changes).

Note also that most modern UIs actually save everything immediately as the user writes it in. You might want to consider doing the same - this is however just a suggestion and I don't think it is required.

**Comment by drwaseemsheikh** [comment]
You are incorrect in your remarks. Every time a patient's record is overwritten, the user is asked for permission because a person could accidentally overwrite a medical record. I believe that dialog box is important to forewarn the user.

I don't have the time to make the changes you ask for and I don't think they affect the functionality of the software.

**Comment by drwaseemsheikh** [comment]
Overwrites are important to tell the user not accidentally overwrite the data.
